import assert from 'node:assert/strict';
import test from 'node:test';
import { attributionTextForScan, containsAttribution, shouldScanAttributionPath } from '../components/attribution-policy.mjs';

test('rejects explicit attribution signatures', () => {
  for (const text of [
    'Co-Authored-By: Claude <bot@example.com>',
    'Co-Authored-By: AI Assistant <ai@example.com>',
    'Assisted-By: LLM <bot@example.com>',
    'Generated with Codex',
    'Made with AI',
    'Built by ChatGPT',
    'Authored by Codex',
    'Codex authored this report',
    'AI-Assisted-By: Claude',
    'Fix auth 🤖',
  ]) assert.equal(containsAttribution(text), true);
});

test('allows legitimate product discussion', () => {
  assert.equal(containsAttribution('Document OpenAI API behavior'), false);
  assert.equal(containsAttribution('Add AI recommendations page'), false);
  assert.equal(containsAttribution('feat: AI-generated summaries endpoint'), false);
  assert.equal(containsAttribution('Document AI-assisted review mode'), false);
  assert.equal(containsAttribution("Claude adapters are generated with Claude's invocation metadata"), false);
  assert.equal(containsAttribution('Status: ready-for-agent'), false);
  assert.equal(containsAttribution('Prepare an agent brief'), false);
});

test('scans repository artifacts while allowing only policy implementation and test fixtures', () => {
  assert.equal(shouldScanAttributionPath('src/comment.ts'), true);
  assert.equal(shouldScanAttributionPath('docs/review.md'), true);
  assert.equal(shouldScanAttributionPath('AGENTS.md'), true);
  assert.equal(shouldScanAttributionPath('nested/CLAUDE.md'), true);
  assert.equal(shouldScanAttributionPath('project/AGENTS.md.template'), true);
  assert.equal(shouldScanAttributionPath('tests/attribution.test.mjs'), false);
  assert.equal(shouldScanAttributionPath('components/attribution-policy.mjs'), false);
  assert.equal(shouldScanAttributionPath('tests/feature.test.mjs'), true);
});

test('policy examples are suppressed without exempting the rest of an agent guide', () => {
  const policy = 'Examples include `Co-Authored-By: Claude`, “Generated by Codex,” or statements that Claude/Codex authored the artifact.';
  assert.equal(containsAttribution(attributionTextForScan('AGENTS.md', policy)), false);
  assert.equal(containsAttribution(attributionTextForScan('AGENTS.md', `${policy}\nGenerated by Codex`)), true);
});
