import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import { spawnSync } from 'node:child_process';

const root = path.resolve(import.meta.dirname, '..');
const read = (relative) => fs.readFile(path.join(root, relative), 'utf8');

async function markdownFiles(entry) {
  const absolute = path.join(root, entry);
  const info = await fs.stat(absolute);
  if (info.isFile()) return [absolute];
  const files = [];
  for (const child of await fs.readdir(absolute, { withFileTypes: true })) {
    if (child.isDirectory()) files.push(...await markdownFiles(path.join(entry, child.name)));
    else if (child.isFile() && child.name.endsWith('.md')) files.push(path.join(absolute, child.name));
  }
  return files;
}

function actionPins(workflow) {
  return new Map(
    [...workflow.matchAll(/^\s*-\s+uses:\s+([^@\s]+)@([0-9a-f]{40})/gm)]
      .map(([, action, sha]) => [action, sha]),
  );
}

test('CI provisions the tools used by the full verification gate', async () => {
  const workflow = await read('.github/workflows/verify.yml');
  assert.match(workflow, /fetch-depth:\s*0/);
  assert.match(workflow, /GITLEAKS_VERSION:\s*"8\.30\.1"/);
  assert.match(workflow, /gitleaks_\$\{GITLEAKS_VERSION\}_linux_x64/);
  assert.match(workflow, /ZIZMOR_VERSION:\s*"1\.29\.0"/);
  assert.match(workflow, /zizmor==\$ZIZMOR_VERSION/);
});

test('portable workflows retain active action pins', async () => {
  const pairs = [
    ['.github/workflows/security.yml', 'project/.github/workflows/harness-security.yml'],
    ['.github/workflows/verify.yml', 'project/.github/workflows/verify.yml'],
  ];

  for (const [activePath, portablePath] of pairs) {
    const activePins = actionPins(await read(activePath));
    const portablePins = actionPins(await read(portablePath));
    for (const [action, sha] of activePins) {
      assert.equal(portablePins.get(action), sha, `${portablePath}: ${action} must match ${activePath}`);
    }
  }
});

test('portable verification retains the active Zizmor version', async () => {
  const active = await read('.github/workflows/verify.yml');
  const portable = await read('project/.github/workflows/verify.yml');
  const version = /ZIZMOR_VERSION:\s*"([^"]+)"/;
  assert.equal(portable.match(version)?.[1], active.match(version)?.[1]);
});

test('the harness repository carries CodeQL and Dependabot', async () => {
  await fs.access(path.join(root, '.github', 'workflows', 'codeql.yml'));
  await fs.access(path.join(root, '.github', 'dependabot.yml'));
});

test('active template text is portable and audits explicit skill ownership', async () => {
  const readme = await read('README.md');
  const audit = await read('scripts/audit.mjs');
  assert.doesNotMatch(readme, /[A-Z]:\\Users\\/i);
  assert.match(audit, /upstream-sources\.json/);
});

test('harness scripts reach Windows tools without a shell', async () => {
  for (const script of ['scripts/machine-setup.mjs', 'scripts/audit.mjs']) {
    const source = await read(script);
    assert.doesNotMatch(source, /ComSpec/);
    assert.doesNotMatch(source, /shell:\s*true/);
    assert.doesNotMatch(source, /'\/d', '\/s', '\/c'/);
  }
});

test('code-review tracker reference is generated by bootstrap', async () => {
  const skill = await read('skills/engineering/code-review/SKILL.md');
  const bootstrap = await read('scripts/bootstrap.mjs');
  assert.match(skill, /docs\/agents\/issue-tracker\.md/);
  assert.match(bootstrap, /docs', 'agents', 'issue-tracker\.md/);
});

test('prototype policy preserves upstream branch isolation', async () => {
  for (const file of ['global/AGENTS.md', 'global/CLAUDE.md', 'project/AGENTS.md.template']) {
    const source = await read(file);
    assert.match(source, /prototype\/<topic>.*default branch/);
    assert.match(source, /Never merge a prototype branch/);
  }
});

test('GitHub hosting requires a working remote or explicit override', async () => {
  const bootstrap = await read('scripts/bootstrap.mjs');
  assert.doesNotMatch(bootstrap, /hasGithubDirectory/);
  assert.match(bootstrap, /githubOverride\s*\|\|\s*ghCheck\.status\s*===\s*0/);
  assert.match(bootstrap, /hasGitHubRemote/);
});

test('generated verification resolves package-manager shims on Windows', async () => {
  const template = await read('project/scripts/verify.mjs.template');
  const bootstrap = await read('scripts/bootstrap.mjs');
  const resolver = await read('scripts/windows-cli.mjs');
  assert.match(resolver, /process\.platform\s*===\s*'win32'/);
  assert.match(template, /\.\.\/\.harness\/runtime\/windows-cli\.mjs/);
  assert.doesNotMatch(template, /function resolveWindowsCli/);
  assert.match(bootstrap, /scripts', 'windows-cli\.mjs/);
  assert.doesNotMatch(template, /ComSpec/);
  assert.doesNotMatch(template, /\['\/d', '\/s', '\/c'/);
  assert.doesNotMatch(template, /shell:\s*true/);
});

test('repository verification retains token-enabled Zizmor audits', async () => {
  const verify = await read('scripts/verify.mjs');
  assert.doesNotMatch(verify, /--no-online-audits/);
  assert.match(verify, /run\('zizmor', \['\.'\]/);
});

test('Windows bootstrap commits normalize Git hook executable modes', async () => {
  const preCommit = await read('components/pre-commit.mjs');
  assert.match(preCommit, /update-index/);
  assert.match(preCommit, /--chmod=\+x/);
});

test('machine audit rejects custom Claude agents', async () => {
  const audit = await read('scripts/audit.mjs');
  assert.match(audit, /\.claude', 'agents'/);
  assert.match(audit, /custom-agent discovery contains/);
});

test('maintainer documentation has no broken relative Markdown links', async () => {
  const files = (await Promise.all(['README.md', 'MACHINE-SETUP.md', 'BOOTSTRAP.md', 'docs/dev'].map(markdownFiles))).flat();
  const trackedResult = spawnSync('git', ['ls-files', '-z'], { cwd: root, encoding: 'utf8' });
  assert.equal(trackedResult.status, 0, trackedResult.stderr);
  const tracked = trackedResult.stdout.split('\0').filter(Boolean).map((entry) => entry.replaceAll('\\', '/'));
  const broken = [];
  for (const file of files) {
    const source = await fs.readFile(file, 'utf8');
    for (const match of source.matchAll(/!?\[[^\]]*\]\(([^)]+)\)/g)) {
      let destination = match[1].trim().replace(/^<|>$/g, '');
      if (!destination || destination.startsWith('#') || /^[a-z][a-z0-9+.-]*:/i.test(destination)) continue;
      destination = decodeURIComponent(destination.split('#')[0]);
      if (!destination) continue;
      const resolved = path.resolve(path.dirname(file), destination);
      const relative = path.relative(root, resolved).replaceAll('\\', '/');
      const inside = relative !== '..' && !relative.startsWith('../') && !path.isAbsolute(relative);
      const versioned = !inside || tracked.includes(relative) || tracked.some((entry) => entry.startsWith(`${relative}/`));
      try {
        await fs.access(resolved);
        if (!versioned) broken.push(`${path.relative(root, file)} -> ${match[1]}`);
      }
      catch { broken.push(`${path.relative(root, file)} -> ${match[1]}`); }
    }
  }
  assert.deepEqual(broken, []);
});
