import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';

const root = path.resolve(import.meta.dirname, '..');
const read = (relative) => fs.readFile(path.join(root, relative), 'utf8');

function actionPins(workflow) {
  return new Map(
    [...workflow.matchAll(/^\s*-\s+uses:\s+([^@\s]+)@([0-9a-f]{40})/gm)]
      .map(([, action, sha]) => [action, sha]),
  );
}

test('CI provisions the tools used by the full verification gate', async () => {
  const workflow = await read('.github/workflows/verify.yml');
  assert.match(workflow, /fetch-depth:\s*0/);
  assert.match(workflow, /GITLEAKS_VERSION:\s*"8\.30\.1"/);
  assert.match(workflow, /gitleaks_\$\{GITLEAKS_VERSION\}_linux_x64/);
  assert.match(workflow, /ZIZMOR_VERSION:\s*"1\.29\.0"/);
  assert.match(workflow, /zizmor==\$ZIZMOR_VERSION/);
});

test('portable workflows retain active action pins', async () => {
  const pairs = [
    ['.github/workflows/security.yml', 'project/.github/workflows/harness-security.yml'],
    ['.github/workflows/verify.yml', 'project/.github/workflows/verify.yml'],
  ];

  for (const [activePath, portablePath] of pairs) {
    const activePins = actionPins(await read(activePath));
    const portablePins = actionPins(await read(portablePath));
    for (const [action, sha] of activePins) {
      assert.equal(portablePins.get(action), sha, `${portablePath}: ${action} must match ${activePath}`);
    }
  }
});

test('portable verification retains the active Zizmor version', async () => {
  const active = await read('.github/workflows/verify.yml');
  const portable = await read('project/.github/workflows/verify.yml');
  const version = /ZIZMOR_VERSION:\s*"([^"]+)"/;
  assert.equal(portable.match(version)?.[1], active.match(version)?.[1]);
});

test('the harness repository carries CodeQL and Dependabot', async () => {
  await fs.access(path.join(root, '.github', 'workflows', 'codeql.yml'));
  await fs.access(path.join(root, '.github', 'dependabot.yml'));
});

test('active template text is portable and audits explicit skill ownership', async () => {
  const readme = await read('README.md');
  const audit = await read('scripts/audit.mjs');
  assert.doesNotMatch(readme, /[A-Z]:\\Users\\/i);
  assert.match(audit, /upstream-sources\.json/);
});

test('harness scripts reach Windows tools without a shell', async () => {
  for (const script of ['scripts/machine-setup.mjs', 'scripts/audit.mjs']) {
    const source = await read(script);
    assert.doesNotMatch(source, /ComSpec/);
    assert.doesNotMatch(source, /shell:\s*true/);
    assert.doesNotMatch(source, /'\/d', '\/s', '\/c'/);
  }
});

test('code-review tracker reference is generated by bootstrap', async () => {
  const skill = await read('skills/engineering/code-review/SKILL.md');
  const bootstrap = await read('scripts/bootstrap.mjs');
  assert.match(skill, /docs\/agents\/issue-tracker\.md/);
  assert.match(bootstrap, /docs', 'agents', 'issue-tracker\.md/);
});

test('prototype policy preserves upstream branch isolation', async () => {
  for (const file of ['global/AGENTS.md', 'global/CLAUDE.md', 'project/AGENTS.md.template']) {
    const source = await read(file);
    assert.match(source, /prototype\/<topic>.*default branch/);
    assert.match(source, /Never merge a prototype branch/);
  }
});

test('GitHub hosting requires a working remote or explicit override', async () => {
  const bootstrap = await read('scripts/bootstrap.mjs');
  assert.doesNotMatch(bootstrap, /hasGithubDirectory/);
  assert.match(bootstrap, /githubOverride\s*\|\|\s*ghCheck\.status\s*===\s*0/);
  assert.match(bootstrap, /hasGitHubRemote/);
});

test('generated verification resolves package-manager shims on Windows', async () => {
  const template = await read('project/scripts/verify.mjs.template');
  const bootstrap = await read('scripts/bootstrap.mjs');
  const resolver = await read('scripts/windows-cli.mjs');
  assert.match(resolver, /process\.platform\s*===\s*'win32'/);
  assert.match(template, /\.\.\/\.harness\/runtime\/windows-cli\.mjs/);
  assert.doesNotMatch(template, /function resolveWindowsCli/);
  assert.match(bootstrap, /scripts', 'windows-cli\.mjs/);
  assert.doesNotMatch(template, /ComSpec/);
  assert.doesNotMatch(template, /\['\/d', '\/s', '\/c'/);
  assert.doesNotMatch(template, /shell:\s*true/);
});

test('repository verification retains token-enabled Zizmor audits', async () => {
  const verify = await read('scripts/verify.mjs');
  assert.doesNotMatch(verify, /--no-online-audits/);
  assert.match(verify, /run\('zizmor', \['\.'\]/);
});

test('Windows bootstrap commits normalize Git hook executable modes', async () => {
  const preCommit = await read('components/pre-commit.mjs');
  assert.match(preCommit, /update-index/);
  assert.match(preCommit, /--chmod=\+x/);
});

test('machine audit rejects custom Claude agents', async () => {
  const audit = await read('scripts/audit.mjs');
  assert.match(audit, /\.claude', 'agents'/);
  assert.match(audit, /custom-agent discovery contains/);
});
