const tool = '(?:Claude|Codex|ChatGPT|Copilot|Cursor|Gemini|Anthropic|OpenAI|GPT(?:-[A-Za-z0-9.]+)?|AI(?: Assistant)?|LLM)';
const patterns = [
  new RegExp(`(?:Co-Authored-By|Assisted-By):[^\\n]*${tool}`, 'i'),
  new RegExp(`AI[- ]Assisted-By:[^\\n]*${tool}`, 'i'),
  new RegExp(`(?:Generated|Created|Written|Authored|Made)\\s+(?:with|by)\\s+(?:an?\\s+)?${tool}(?!['’]s)`, 'i'),
  new RegExp(`Built\\s+by\\s+(?:an?\\s+)?${tool}(?!['’]s)`, 'i'),
  new RegExp(`${tool}\\s+(?:authored|generated|created|wrote)\\s+(?:this|the|an?)\\s+(?:artifact|file|code|review|report|document|pull request|PR|commit|comment)`, 'i'),
  /🤖/u,
];

export function containsAttribution(text) {
  return patterns.some((pattern) => pattern.test(text));
}

export function shouldScanAttributionPath(filePath) {
  const normalized = filePath.replaceAll('\\', '/');
  if (['components/attribution-policy.mjs', 'components/check-attribution.mjs', '.harness/hooks/attribution-policy.mjs', '.harness/hooks/check-attribution.mjs'].includes(normalized)) return false;
  if (/(?:^|\/)tests\/attribution\.test\.mjs$/i.test(normalized)) return false;
  return true;
}

export function attributionTextForScan(filePath, text) {
  if (!/(?:^|\/)(?:AGENTS|CLAUDE)\.md(?:\.template)?$/i.test(filePath.replaceAll('\\', '/'))) return text;
  return text
    .replaceAll('`Co-Authored-By: Claude`', '<forbidden commit trailer example>')
    .replaceAll('“Generated by Codex,”', '<forbidden generation marker example>')
    .replaceAll('"Generated by Codex,"', '<forbidden generation marker example>')
    .replaceAll('statements that Claude/Codex authored the artifact', '<forbidden authorship statement example>');
}
